In [1]:
import numpy as np 

[NumPy](http://www.numpy.org/) usage: 

- Mathematical and logical operations on arrays.
- Fourier transforms and routines for shape manipulation.
- Operations related to linear algebra. NumPy has in-built functions for linear algebra and random number generatio

In [4]:
a = np.array([[1,2,3],[4,5,6]]) 
print(a)

[[1 2 3]
 [4 5 6]]


In [5]:
print(a.shape)

(2, 3)


In [6]:
print(type(a))

<class 'numpy.ndarray'>


In [8]:
np_list = np.arange(10)
np_list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.random.seed(2020)

inx_list = np.arange(len(my_list))
np.random.shuffle(np_list)

mixed_list = np_list[inx_list] 
mixed_list

array([7, 9, 6, 3, 4, 1, 5, 8, 2, 0])