In [1]:
import numpy as np 

[NumPy](http://www.numpy.org/) usage: 

- Mathematical and logical operations on arrays.
- Fourier transforms and routines for shape manipulation.
- Operations related to linear algebra. NumPy has in-built functions for linear algebra and random number generatio

In [ ]:
#http://cs231n.github.io/python-numpy-tutorial/

In [4]:
a = np.array([[1,2,3],[4,5,6]]) 
print(a)

[[1 2 3]
 [4 5 6]]


In [5]:
print(a.shape)

(2, 3)


In [6]:
print(type(a))

<class 'numpy.ndarray'>


In [8]:
np_list = np.arange(10)
np_list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.random.seed(2020)

inx_list = np.arange(len(my_list))
np.random.shuffle(np_list)

mixed_list = np_list[inx_list] 
mixed_list

array([7, 9, 6, 3, 4, 1, 5, 8, 2, 0])

Log

In [11]:
log_value = np.log2( 100 )
np.exp2( log_value )

99.99999999999999

vector

In [15]:
np_list

array([7, 9, 6, 3, 4, 1, 5, 8, 2, 0])

In [16]:
print(type(np_list))

<class 'numpy.ndarray'>


In [17]:
np.array([x*2 for x in np_list])

array([14, 18, 12,  6,  8,  2, 10, 16,  4,  0])

In [18]:
np_list*2

array([14, 18, 12,  6,  8,  2, 10, 16,  4,  0])

Ufunc

In [19]:
np_list

array([7, 9, 6, 3, 4, 1, 5, 8, 2, 0])

In [20]:
np_list+np_list

array([14, 18, 12,  6,  8,  2, 10, 16,  4,  0])

Filtr

In [21]:
short_list = np.array([10, 5, 8])

In [22]:
short_list[ [2, 0, 1] ] #indexes 

array([ 8, 10,  5])

In [23]:
short_list[ [True, False, True] ]

array([10,  8])

In [24]:
short_list == 10 #where is 10

array([ True, False, False])

In [26]:
short_list[ short_list == 8 ] # only 8

array([8])

In [27]:
# normally [x*2 for x in my_list if x % 2 == 0]
my_list[ my_list % 2 == 0 ] * 2

array([ 0,  4,  8, 12, 16])

In [28]:
my_list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
my_filter = my_list % 2 == 0
my_list[ my_filter ] * 2

array([ 0,  4,  8, 12, 16])

In [30]:
my_list[ (my_list < 3) | (my_list > 6) ]

array([0, 1, 2, 7, 8, 9])